version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            yarn --ignore-engines
      - run:
          name: test
          command: yarn test

  deploy:
    executor: heroku/default

    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - run_tests

      - deploy:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - dev
