version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            yarn --ignore-engines

  deploy:
    executor: heroku/default
    branches:
      only:
        - dev
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  build_test:
    jobs:
      - run_tests
  heroku_deploy:
    jobs:
      - deploy
